spring.application.name=matchmaking-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/matchmaking_backend
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

app.jwt.secret=matchmaking-dev-secret-key-very-long-1234567890
