# Dev profile - H2 in-memory database
spring.datasource.url=jdbc:postgresql://localhost:5432/matchmaking_dev
spring.datasource.username=matchmaking
spring.datasource.password=matchmaking



spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true
spring.h2.console.path=/h2-console

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Health check detalhado
management.endpoint.health.show-details=when-authorized
management.endpoint.health.show-components=always

